CREATE OR REPLACE STREAM RAW_LAYER.PRC_BENCHMARK_STREAM
  ON TABLE RAW_LAYER.PRC_BENCHMARK_RAW
  SHOW_INITIAL_ROWS = FALSE;

CREATE OR REPLACE STREAM RAW_LAYER.PRC_CAMPAIGN_STREAM
  ON TABLE RAW_LAYER.PRC_CAMPAIGN_RAW
  SHOW_INITIAL_ROWS = FALSE;