create or replace TABLE SILVER_LAYER.DIM_pp (
	PRICINGBENCHMARKPRCINTKEY NUMBER NOT NULL,
	PRICINGBENCHMARKPRCKEY VARCHAR NOT NULL,
    ENCHMARKPRCKEY VARCHAR NOT NULL,
    dddd VARCHAR NOT NULL,
    dssd VARCHAR NOT NULL,
    kk VARCHAR NOT NULL,
    pp VARCHAR NOT NULL
	
	primary key (PRICINGBENCHMARKPRCINTKEY)
);