create or replace TABLE SILVER_LAYER.DIM_pp (
	PRICINGBENCHMARKPRCINTKEY NUMBER NOT NULL,
	PRICINGBENCHMARKPRCKEY VARCHAR NOT NULL,
	APUKCODE VARCHAR NOT NULL,
	ANABENCH2 VARCHAR NOT NULL,
	SKUGROUP VARCHAR,
    SYS_SOURCE_DATE	VARCHAR,
	SYS_DATE_CREATE TIMESTAMP_LTZ(9) NOT NULL,
	primary key (PRICINGBENCHMARKPRCINTKEY)
);