create or replace TABLE SILVER_LAYER.DIM_pp (
	PRICINGBENCHMARKPRCINTKEY NUMBER NOT NULL,
	PRICINGBENCHMARKPRCKEY VARCHAR NOT NULL,
    ENCHMARKPRCKEY VARCHAR NOT NULL
	
	primary key (PRICINGBENCHMARKPRCINTKEY)
);