CREATE OR REPLACE TASK pipeline_raw_to_gold
  WAREHOUSE = …
  SCHEDULE  = 'USING CRON * * * * * UTC'
  WHEN SYSTEM$STREAM_HAS_DATA('RAW_LAYER.PRC_CAMPAIGN_RAW_STREAM')
    OR SYSTEM$STREAM_HAS_DATA('RAW_LAYER.PRC_BENCHMARK_RAW_STREAM')
AS
CALL process_all();
