CREATE OR REPLACE TASK GOLD_LAYER.PIPE_LOAD_RAW_TO_GOLD
  WAREHOUSE = TEST_WH
  SCHEDULE  = 'USING CRON */5 * * * * UTC'
  WHEN SYSTEM$STREAM_HAS_DATA('RAW_LAYER.PRC_CAMPAIGN_RAW_STREAM')
    OR SYSTEM$STREAM_HAS_DATA('RAW_LAYER.PRC_BENCHMARK_RAW_STREAM')
AS
  CALL process_all();