CREATE OR REPLACE PROCEDURE SILVER_LAYER.process_bronze_to_silver()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
-- From: merge_bronze_to_silver_prc_benchmark.sql
MERGE INTO SILVER_LAYER.DIM_PRC_BENCHMARK_SLV AS TARGET
USING (
    SELECT *
    FROM (
        SELECT
            -- Clé technique (HASH)
            TO_NUMERIC(HASH(
                COALESCE(APUKCODE, 'N/A') || '_' || COALESCE(ANABENCH2, 'N/A')
            )) AS PRICINGBENCHMARKPRCINTKEY,

            -- Clé fonctionnelle concaténée et nettoyée
            REPLACE(
                COALESCE(APUKCODE, 'N/A') || '_' || COALESCE(ANABENCH2, 'N/A'),
                ' ',
                '_'
            ) AS PRICINGBENCHMARKPRCKEY,

            APUKCODE,
            ANABENCH2,
            SKUGROUP,
            SYS_SOURCE_DATE,
            CURRENT_TIMESTAMP() AS SYS_DATE_CREATE,

            -- Pour garder une seule ligne par clé
            ROW_NUMBER() OVER (
                PARTITION BY 
                    TO_NUMERIC(HASH(COALESCE(APUKCODE, 'N/A') || '_' || COALESCE(ANABENCH2, 'N/A')))
                ORDER BY 
                    TRY_TO_TIMESTAMP(SYS_SOURCE_DATE) DESC NULLS LAST,
                    CURRENT_TIMESTAMP() DESC
            ) AS row_num
        --FROM BRONZE_LAYER.PRC_BENCHMARK_BRZ
        FROM BRONZE_LAYER.PRC_BENCHMARK_BRZ_STREAM
    )
    WHERE row_num = 1
) AS SOURCE

ON TARGET.PRICINGBENCHMARKPRCINTKEY = SOURCE.PRICINGBENCHMARKPRCINTKEY

WHEN MATCHED THEN UPDATE SET
    TARGET.PRICINGBENCHMARKPRCKEY = SOURCE.PRICINGBENCHMARKPRCKEY,
    TARGET.APUKCODE = SOURCE.APUKCODE,
    TARGET.ANABENCH2 = SOURCE.ANABENCH2,
    TARGET.SKUGROUP = SOURCE.SKUGROUP,
    TARGET.SYS_SOURCE_DATE = SOURCE.SYS_SOURCE_DATE,
    TARGET.SYS_DATE_CREATE = SOURCE.SYS_DATE_CREATE

WHEN NOT MATCHED THEN INSERT (
    PRICINGBENCHMARKPRCINTKEY,
    PRICINGBENCHMARKPRCKEY,
    APUKCODE,
    ANABENCH2,
    SKUGROUP,
    SYS_SOURCE_DATE,
    SYS_DATE_CREATE
) VALUES (
    SOURCE.PRICINGBENCHMARKPRCINTKEY,
    SOURCE.PRICINGBENCHMARKPRCKEY,
    SOURCE.APUKCODE,
    SOURCE.ANABENCH2,
    SOURCE.SKUGROUP,
    SOURCE.SYS_SOURCE_DATE,
    SOURCE.SYS_DATE_CREATE
);

-- From: merge_bronze_to_silver_prc_campaign.sql
MERGE INTO SILVER_LAYER.DIM_PRC_CAMPAIGN_SLV AS tgt
USING (
    SELECT
        HASH(HOUSEKEY || '_' || CAMPAIGNCODE) AS PRICINGCAMPAIGNPRCINTKEY,
        COALESCE(CAMPAIGNCODE, 'N/A') || '_' || COALESCE(CAMPAIGNNAME, 'N/A') AS PRICINGCAMPAIGNPRCKEY,
        HOUSEKEY,
        CAMPAIGNCODE,
        CAMPAIGNNAME,
        CAMPAIGNDESCRIPTION,
        HISTORICALSELLINFIRSTMONTH,
        HISTORICALSELLINLASTMONTH,
        CAMPAIGNDATE,
        CAST(TO_TIMESTAMP_TZ(SYS_SOURCE_DATE, 'YYYY-MM-DD HH24:MI:SS.FF3 TZD') AS TIMESTAMP_LTZ) AS SYS_SOURCE_DATE,
        CURRENT_TIMESTAMP() AS SYS_DATE_CREATE
    --FROM BRONZE_LAYER.PRC_CAMPAIGN_BRZ
    FROM BRONZE_LAYER.PRC_CAMPAIGN_BRZ_STREAM
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY HOUSEKEY, CAMPAIGNCODE 
        ORDER BY CREATE_DATE DESC
    ) = 1
) AS src
ON tgt.PRICINGCAMPAIGNPRCINTKEY = src.PRICINGCAMPAIGNPRCINTKEY

WHEN MATCHED THEN UPDATE SET
    PRICINGCAMPAIGNPRCKEY        = src.PRICINGCAMPAIGNPRCKEY,
    HOUSEKEY                     = src.HOUSEKEY,
    CAMPAIGNCODE                 = src.CAMPAIGNCODE,
    CAMPAIGNNAME                 = src.CAMPAIGNNAME,
    CAMPAIGNDESCRIPTION          = src.CAMPAIGNDESCRIPTION,
    HISTORICALSELLINFIRSTMONTH  = src.HISTORICALSELLINFIRSTMONTH,
    HISTORICALSELLINLASTMONTH   = src.HISTORICALSELLINLASTMONTH,
    CAMPAIGNDATE                 = src.CAMPAIGNDATE,
    SYS_SOURCE_DATE              = src.SYS_SOURCE_DATE

WHEN NOT MATCHED THEN INSERT (
    PRICINGCAMPAIGNPRCINTKEY,
    PRICINGCAMPAIGNPRCKEY,
    HOUSEKEY,
    CAMPAIGNCODE,
    CAMPAIGNNAME,
    CAMPAIGNDESCRIPTION,
    HISTORICALSELLINFIRSTMONTH,
    HISTORICALSELLINLASTMONTH,
    CAMPAIGNDATE,
    SYS_SOURCE_DATE,
    SYS_DATE_CREATE
)
VALUES (
    src.PRICINGCAMPAIGNPRCINTKEY,
    src.PRICINGCAMPAIGNPRCKEY,
    src.HOUSEKEY,
    src.CAMPAIGNCODE,
    src.CAMPAIGNNAME,
    src.CAMPAIGNDESCRIPTION,
    src.HISTORICALSELLINFIRSTMONTH,
    src.HISTORICALSELLINLASTMONTH,
    src.CAMPAIGNDATE,
    src.SYS_SOURCE_DATE,
    src.SYS_DATE_CREATE
);


  RETURN 'SILVER_LAYER.process_bronze_to_silver terminé';
END;
$$;
