--- BronzeLayer

CREATE OR REPLACE TABLE BRONZE_LAYER.PRC_BENCHMARK_BRZ
(
  APUKCode VARCHAR not null,
  Anabench2Code VARCHAR not null,
  Anabench2 VARCHAR,
  SKUGroup VARCHAR,
  SYS_SOURCE_DATE VARCHAR,
  CREATE_DATE TIMESTAMP_LTZ COMMENT 'valued with Copy into command metadata',
  file_name VARCHAR COMMENT 'valued with Copy into command metadata',
  PRIMARY KEY(APUKCODE, Anabench2Code)
);




create or replace TABLE BRONZE_LAYER.PRC_CAMPAIGN_BRZ (
	HOUSEKEY VARCHAR(16777216) NOT NULL,
	CAMPAIGNCODE VARCHAR(16777216) NOT NULL,
	CAMPAIGNNAME VARCHAR(16777216),
	CAMPAIGNDESCRIPTION VARCHAR(16777216),
	HISTORICALSELLINFIRSTMONTH VARCHAR(16777216),
	HISTORICALSELLINLASTMONTH VARCHAR(16777216),
	CAMPAIGNDATE VARCHAR(16777216),
  SYS_SOURCE_DATE VARCHAR(16777216),
  CREATE_DATE TIMESTAMP_LTZ, -- valued with copy into command metadata
  file_name VARCHAR(16777216), -- valued with copy into command metadata
	primary key (HOUSEKEY, CAMPAIGNCODE)
);