MERGE INTO SILVER_LAYER.DIM_PRC_CAMPAIGN_SLV AS tgt
USING (
    SELECT
        HASH(HOUSEKEY || '_' || CAMPAIGNCODE) AS PRICINGCAMPAIGNPRCINTKEY,
        COALESCE(CAMPAIGNCODE, 'N/A') || '_' || COALESCE(CAMPAIGNNAME, 'N/A') AS PRICINGCAMPAIGNPRCKEY,
        HOUSEKEY,
        CAMPAIGNCODE,
        CAMPAIGNNAME,
        CAMPAIGNDESCRIPTION,
        HISTORICALSELLINFIRSTMONTH,
        HISTORICALSELLINLASTMONTH,
        CAMPAIGNDATE,
        CAST(TO_TIMESTAMP_TZ(SYS_SOURCE_DATE, 'YYYY-MM-DD HH24:MI:SS.FF3 TZD') AS TIMESTAMP_LTZ) AS SYS_SOURCE_DATE,
        CURRENT_TIMESTAMP() AS SYS_DATE_CREATE
    --FROM BRONZE_LAYER.PRC_CAMPAIGN_BRZ
    FROM BRONZE_LAYER.PRC_CAMPAIGN_BRZ_STREAM
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY HOUSEKEY, CAMPAIGNCODE 
        ORDER BY CREATE_DATE DESC
    ) = 1
) AS src
ON tgt.PRICINGCAMPAIGNPRCINTKEY = src.PRICINGCAMPAIGNPRCINTKEY

WHEN MATCHED THEN UPDATE SET
    PRICINGCAMPAIGNPRCKEY        = src.PRICINGCAMPAIGNPRCKEY,
    HOUSEKEY                     = src.HOUSEKEY,
    CAMPAIGNCODE                 = src.CAMPAIGNCODE,
    CAMPAIGNNAME                 = src.CAMPAIGNNAME,
    CAMPAIGNDESCRIPTION          = src.CAMPAIGNDESCRIPTION,
    HISTORICALSELLINFIRSTMONTH  = src.HISTORICALSELLINFIRSTMONTH,
    HISTORICALSELLINLASTMONTH   = src.HISTORICALSELLINLASTMONTH,
    CAMPAIGNDATE                 = src.CAMPAIGNDATE,
    SYS_SOURCE_DATE              = src.SYS_SOURCE_DATE

WHEN NOT MATCHED THEN INSERT (
    PRICINGCAMPAIGNPRCINTKEY,
    PRICINGCAMPAIGNPRCKEY,
    HOUSEKEY,
    CAMPAIGNCODE,
    CAMPAIGNNAME,
    CAMPAIGNDESCRIPTION,
    HISTORICALSELLINFIRSTMONTH,
    HISTORICALSELLINLASTMONTH,
    CAMPAIGNDATE,
    SYS_SOURCE_DATE,
    SYS_DATE_CREATE
)
VALUES (
    src.PRICINGCAMPAIGNPRCINTKEY,
    src.PRICINGCAMPAIGNPRCKEY,
    src.HOUSEKEY,
    src.CAMPAIGNCODE,
    src.CAMPAIGNNAME,
    src.CAMPAIGNDESCRIPTION,
    src.HISTORICALSELLINFIRSTMONTH,
    src.HISTORICALSELLINLASTMONTH,
    src.CAMPAIGNDATE,
    src.SYS_SOURCE_DATE,
    src.SYS_DATE_CREATE
);
